import { Mistral } from '@mistralai/mistralai'

if (!process.env.MISTRAL_API_KEY) {
    console.warn('MISTRAL_API_KEY is not set. SEO generation will not work.')
}

export const mistral = new Mistral({
    apiKey: process.env.MISTRAL_API_KEY ?? '',
})

/**
 * Complete SEO metadata generated by AI
 */
export type SEOMetadata = {
    metaTitle: string
    metaDescription: string
    excerpt: string
    keywords: string[]
    suggestedTags: string[]
    mainImageAlt: string
    mainImageCaption: string
    shareImageAlt: string
}

/**
 * SEO Generation Prompt
 * 
 * This prompt instructs Mistral to generate all SEO-related text fields
 * for a blog post. The AI analyzes the title, content, and image context
 * to produce optimized metadata.
 */
const SEO_GENERATION_PROMPT = `You are an expert SEO specialist and content strategist. Your task is to generate comprehensive SEO metadata for a blog post.

Given the post title, content, and optional image filename, generate ALL of the following fields:

## Required Output (JSON object):

1. **metaTitle** (max 60 characters)
   - SEO-optimized title for search engines
   - Include primary keyword naturally
   - Should be compelling and click-worthy
   - Different from the editorial title if needed for SEO

2. **metaDescription** (max 160 characters)
   - Compelling SERP snippet description
   - Include a call-to-action or value proposition
   - Naturally incorporate primary keyword
   - Entice users to click through

3. **excerpt** (max 200 characters)
   - Concise summary for listings and RSS feeds
   - Captures the essence of the article
   - Works as fallback for metaDescription

4. **keywords** (array of 5-8 strings)
   - Relevant keywords for internal tagging
   - Include primary, secondary, and long-tail keywords
   - Mix of broad and specific terms

5. **suggestedTags** (array of 3-5 strings)
   - Topic tags like "Next.js", "React", "Web Development"
   - Specific technologies, concepts, or themes mentioned

6. **mainImageAlt** (concise, descriptive)
   - Accessibility text for the main image
   - Describe what the image shows
   - Include relevant keywords naturally

7. **mainImageCaption** (engaging, informative)
   - Visible caption below the image
   - Add context or interesting details
   - Can be slightly longer and more descriptive

8. **shareImageAlt** (concise, descriptive)
   - Alt text for social media share image
   - Focus on what appears in the preview

## Guidelines:
- Be specific and unique to this content
- Avoid generic phrases like "Learn more" or "Click here"
- Use active voice and power words
- Ensure all text is grammatically correct
- If no image info provided, create contextually appropriate alt/caption based on content

Respond ONLY with valid JSON, no additional text or explanation.`

export async function generateSEOMetadata(
    title: string,
    content: string,
    imageFilename?: string
): Promise<SEOMetadata> {
    const userMessage = `
Title: ${title}

Content:
${content.slice(0, 3000)}

${imageFilename ? `Main Image Filename: ${imageFilename}` : 'No image filename provided - generate alt/caption based on content context.'}
`.trim()

    const result = await mistral.chat.complete({
        model: 'mistral-large-latest',
        messages: [
            { role: 'system', content: SEO_GENERATION_PROMPT },
            { role: 'user', content: userMessage },
        ],
        responseFormat: { type: 'json_object' },
    })

    const messageContent = result.choices?.[0]?.message?.content
    const responseText = typeof messageContent === 'string'
        ? messageContent
        : '{}'

    try {
        const parsed = JSON.parse(responseText)

        // Ensure all fields exist with fallbacks
        return {
            metaTitle: parsed.metaTitle || title.slice(0, 60),
            metaDescription: parsed.metaDescription || content.slice(0, 160),
            excerpt: parsed.excerpt || content.slice(0, 200),
            keywords: parsed.keywords || [],
            suggestedTags: parsed.suggestedTags || [],
            mainImageAlt: parsed.mainImageAlt || `Image for ${title}`,
            mainImageCaption: parsed.mainImageCaption || '',
            shareImageAlt: parsed.shareImageAlt || `${title} - Social Preview`,
        }
    } catch {
        // Fallback if JSON parsing fails
        return {
            metaTitle: title.slice(0, 60),
            metaDescription: content.slice(0, 160),
            excerpt: content.slice(0, 200),
            keywords: [],
            suggestedTags: [],
            mainImageAlt: `Image for ${title}`,
            mainImageCaption: '',
            shareImageAlt: `${title} - Social Preview`,
        }
    }
}

/**
 * Generate only image-related SEO fields
 * Useful when adding/updating images after initial post creation
 */
export async function generateImageSEO(
    postTitle: string,
    postExcerpt: string,
    imageFilename?: string
): Promise<{ alt: string; caption: string }> {
    const prompt = `Generate SEO-optimized alt text and caption for a blog post image.

Post Title: ${postTitle}
Post Summary: ${postExcerpt}
${imageFilename ? `Image Filename: ${imageFilename}` : ''}

Return JSON with:
- alt: Concise, descriptive alt text for accessibility and SEO
- caption: Engaging visible caption for below the image

Respond ONLY with valid JSON.`

    const result = await mistral.chat.complete({
        model: 'mistral-large-latest',
        messages: [{ role: 'user', content: prompt }],
        responseFormat: { type: 'json_object' },
    })

    const messageContent = result.choices?.[0]?.message?.content
    const responseText = typeof messageContent === 'string'
        ? messageContent
        : '{}'

    try {
        const parsed = JSON.parse(responseText)
        return {
            alt: parsed.alt || `Image for ${postTitle}`,
            caption: parsed.caption || '',
        }
    } catch {
        return {
            alt: `Image for ${postTitle}`,
            caption: '',
        }
    }
}
